wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.8.5
    cli_version: 0.14.2
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1681545232.578209
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 1
      - 23
      4: 3.8.5
      5: 0.14.2
      8:
      - 5
seed:
  desc: null
  value: 42
epochs:
  desc: null
  value: 50
dataset:
  desc: null
  value: MaskBaseDataset
augmentation:
  desc: null
  value: BaseAugmentation
resize:
  desc: null
  value:
  - 128
  - 96
batch_size:
  desc: null
  value: 64
valid_batch_size:
  desc: null
  value: 1000
model:
  desc: null
  value: BaseModel
optimizer:
  desc: null
  value: RMSprop
lr:
  desc: null
  value: 0.001
val_ratio:
  desc: null
  value: 0.2
criterion:
  desc: null
  value: cross_entropy
lr_decay_step:
  desc: null
  value: 20
log_interval:
  desc: null
  value: 20
name:
  desc: null
  value: proj_test_RMSProp
project:
  desc: null
  value: test_project
model_dir:
  desc: null
  value: /opt/ml/workspace/model
data_dir:
  desc: null
  value: /opt/ml/input/data/train/images
