wandb_version: 1

batch_size:
  desc: null
  value: 256
lr:
  desc: null
  value: 2.0e-05
epochs:
  desc: null
  value: 10
name:
  desc: null
  value: '56'
criterion_name:
  desc: null
  value: CrossEntropyLoss()
_wandb:
  desc: null
  value:
    python_version: 3.8.16
    cli_version: 0.14.2
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1681808504.357038
    t:
      1:
      - 1
      - 5
      - 41
      - 49
      - 51
      - 53
      - 55
      - 63
      - 80
      2:
      - 1
      - 5
      - 41
      - 49
      - 51
      - 53
      - 55
      - 63
      - 80
      3:
      - 2
      - 13
      - 16
      - 23
      4: 3.8.16
      5: 0.14.2
      8:
      - 5
