wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.8.16
    cli_version: 0.14.2
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1681947979.791803
    t:
      1:
      - 1
      - 5
      - 35
      - 41
      - 49
      - 51
      - 53
      - 55
      - 63
      - 80
      2:
      - 1
      - 5
      - 35
      - 41
      - 49
      - 51
      - 53
      - 55
      - 63
      - 80
      3:
      - 2
      - 23
      4: 3.8.16
      5: 0.14.2
      8:
      - 5
